[package]
name = "sourcemap"
version = "0.7.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["javascript", "sourcemap", "sourcemaps"]
description = "Basic sourcemap handling for Rust"
homepage = "https://github.com/mitsuhiko/rust-sourcemap"
documentation = "http://mitsuhiko.github.io/rust-sourcemap/"
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_derive"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_json = "0.8"
base64 = "0.1.1"
