[package]
name = "sourcemap"
version = "0.3.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["javascript", "sourcemap", "sourcemaps"]
description = "Basic sourcemap handling for Rust"
homepage = "https://github.com/mitsuhiko/rust-sourcemap"
documentation = "http://mitsuhiko.github.io/rust-sourcemap/"
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "~0.7.0", optional = true }
syntex = "0.33.0"

[dependencies]
serde = "~0.7.0"
serde_json = "~0.7.1"
serde_macros = { version = "~0.7.0", optional = true }
base64 = "0.1.1"
