[package]
name = "sourcemap"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[dependencies]
serde = "0.7.5"
serde_json = "0.7.1"
